version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: xyz-mongo-development
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
